#!/usr/bin/env python3
"""Dump holdings + strategy timelines and the README hero chart
from the logged PIT run. Reuses the exact engine; no re-search."""
import os, numpy as np, pandas as pd
import walkforward_study as ws
from make_report import parse_spec, load_mode_data, benchmark_curve

OUT = "repo_out"; os.makedirs(OUT, exist_ok=True)

# human-readable decoding helpers ------------------------------------------
SIG_DESC = {}  # filled lazily only for the timeline; names are self-describing
UNIV = {"all": "full universe", "highvol": "above-median volatility names",
        "lowvol": "below-median volatility names"}

def describe(name):
    blend, universe, n, conds, gates = parse_spec(name)
    s = " + ".join(blend)
    d = f"top {n} by **{s}** within {UNIV[universe]}"
    if conds: d += "; holdings must satisfy " + ", ".join(f"`{c}`" for c in conds)
    if gates: d += "; cash when " + ", ".join(f"`{g}`" for g in gates) + " is off"
    return d

L = pd.read_csv("study_log_pit.csv", parse_dates=["deploy_from"])
close, volume, member = load_mode_data("pit", synthetic=False)
eng = ws.Engine(close, volume, member)
end = close.index[-1]

eq = pd.read_csv("study_equity_pit.csv", index_col=0, parse_dates=True).iloc[:, 0]
bench, blab = benchmark_curve(close, member, eq.index)

# ---------------------------------------------------------------- holdings
rows_md, rows_csv = [], []
for _, row in L.iterrows():
    dep0 = pd.Timestamp(row["deploy_from"])
    dep1 = min(dep0 + pd.DateOffset(months=6), end + pd.Timedelta(days=1))
    spec = parse_spec(row["winner"])
    dd = eng.fortnights[(eng.fortnights >= dep0) & (eng.fortnights < dep1)]
    wbd = eng.weights(spec, dd)
    rows_md.append(f"\n### {dep0.date()} → {dep1.date()}  —  `{row['winner']}`\n")
    rows_md.append(describe(row["winner"]) + "\n")
    rows_md.append("| Rebalance date | Holdings (equal-weighted) |")
    rows_md.append("|---|---|")
    for dte in dd:
        h = wbd.get(dte, pd.Series(dtype=float))
        names = ", ".join(t.replace(".NS","") for t in h.index) if len(h) else "**CASH** (gate off)"
        rows_md.append(f"| {dte.date()} | {names} |")
        for t in ([x.replace(".NS","") for x in h.index] if len(h) else ["CASH"]):
            rows_csv.append({"rebalance_date": dte.date(), "window_start": dep0.date(),
                             "strategy": row["winner"], "ticker": t,
                             "weight": round(1.0/len(h), 4) if len(h) else 0.0})

hdr = """# Holdings timeline — point-in-time walk-forward run

Every position the strategy actually held, at every fortnightly rebalance,
reconstructed deterministically from the logged winning strategies
(`verification/study_log_pit.csv`) and the shipped price/membership data.
Positions are equal-weighted within each basket. **CASH** rows are rebalances
where the winner's market gate was off.

Machine-readable version: [`holdings_timeline.csv`](holdings_timeline.csv).
Tickers are NSE symbols at their current names (historical renames are mapped
to the surviving symbol, e.g. MOTHERSUMI → MOTHERSON).

Generated by `scripts/dump_timelines.py` — rerun it to regenerate this file.
"""
with open(os.path.join(OUT, "HOLDINGS_TIMELINE.md"), "w") as f:
    f.write(hdr + "\n".join(rows_md) + "\n")
pd.DataFrame(rows_csv).to_csv(os.path.join(OUT, "holdings_timeline.csv"), index=False)

# ------------------------------------------------------- strategy timeline
tl = ["""# Strategy timeline — which strategy traded when

At each 6-month boundary a tournament over ~580 candidates on the trailing
2 years crowns one winner, which then trades unchanged for the next 6 months.
This is the complete sequence of winners from the point-in-time run, with the
training-window return that won the tournament and the out-of-sample return
the strategy then actually delivered.

The gap between those two columns is the honest cost of selection bias:
the tournament crowns a lucky extreme, and reality regresses it.
""",
"| # | Deployed from | Style family | Winning strategy | Trained 2y | Deployed 6m |",
"|---|---|---|---|---|---|"]
for i, row in L.iterrows():
    tl.append(f"| {i+1} | {row['deploy_from'].date()} | {row['style']} | "
              f"`{row['winner']}` | {row['trained_2y_%']:+.1f}% | {row['deployed_6m_%']:+.1f}% |")
tl.append("\n## Decoded\n")
for i, row in L.iterrows():
    tl.append(f"**{i+1}. {row['deploy_from'].date()}** — {describe(row['winner'])}\n")
tl.append("""
## Reading notes

- `&` joins two signals into an equal-weighted z-score blend; `|` separates
  the blend from stock-level conditions and market gates; `+` chains several.
- No strategy family dominates: flow/illiquidity blends own 2016–2019,
  contrarian `bb_lower` owns the COVID windows, quality/trend blends own
  2021–2026. The rotation *is* the system.
- Trained ≫ deployed in every window, as expected from a ~580-candidate
  tournament. The claim is the sum of the deployed column, never the trained one.

Full definitions of every signal, condition and gate: [STRATEGY_UNIVERSE.md](STRATEGY_UNIVERSE.md).
""")
with open(os.path.join(OUT, "STRATEGY_TIMELINE.md"), "w") as f:
    f.write("\n".join(tl))

# ------------------------------------------------------------- hero chart
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
SURFACE, INK, MUT, GRID = "#fcfcfb", "#0b0b0b", "#898781", "#e1e0d9"
C_STRAT, C_BENCH = "#2a78d6", "#1baf7a"
plt.rcParams.update({"figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
    "axes.edgecolor": GRID, "axes.labelcolor": MUT, "xtick.color": MUT,
    "ytick.color": MUT, "text.color": INK, "font.size": 11, "axes.grid": True,
    "grid.color": GRID, "grid.linewidth": 0.6, "axes.spines.top": False,
    "axes.spines.right": False, "legend.frameon": False,
    "font.family": "sans-serif"})
fig, ax = plt.subplots(figsize=(10, 5), dpi=150)
ax.plot(eq.index, eq/1e7, color=C_STRAT, lw=2.0,
        label="walk-forward strategy (0.1%/leg costs)")
ax.plot(bench.index, bench/1e7, color=C_BENCH, lw=1.8,
        label="eq-wt basket, same point-in-time universe")
ax.set_yscale("log"); ax.set_yticks([1, 2, 5, 10, 20])
ax.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:g}x"))
ax.set_title("Growth of ₹1 crore, 2015–2026 — fully out-of-sample, point-in-time universe",
             color=INK, fontsize=12, pad=12, loc="left")
ax.legend(loc="upper left")
for s in ("left", "bottom"): ax.spines[s].set_color("#c3c2b7")
fig.tight_layout()
fig.savefig(os.path.join(OUT, "equity_curve.png"))
print("final", f"{eq.iloc[-1]:,.0f}", "| bench", f"{bench.iloc[-1]:,.0f}",
      "| csv rows", len(rows_csv), "| windows", len(L))
